sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nohup webdriver-manager start &
  - sleep 3000

install:
  - npm install
  - npm install -g protractor
  - webdriver-manager update

script:
  - npm test