sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nohup webdriver-manager start &
  - git clone https://github.com/upgundecha/das-boot.git
  - cd das-boot
  - nohup mvn spring-boot:run &
  - sleep 15
  - cd ..

install:
  - npm install
  - npm install -g protractor
  - webdriver-manager update

script:
  - npm test